### ISSUE TITLE
Support more version of Golang

### ISSUE THREAD

**Issue by ValentinMontmirail** [ahuigo/gofnext#3]
Hello,

I think the library would benefit of supporting more version of Go than just the latest (`1.21`).
I would suggest replacing the automatic testing by the following Github Action:

```
name: Tests

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: [6, 7]
        go-version: ['1.18', '1.19', '1.20', '1.21']
    steps:
    - uses: actions/checkout@v2
   
    - name: Start Redis
      uses: supercharge/redis-github-action@1.7.0
      with:
        redis-version: ${{ matrix.redis-version }}
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Test
      run: make test

    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./cover.out
        flags: unittests
        verbose: true
```

Additionnally, we should change the version of go inside the `go.mod` to 1.18

https://github.com/ahuigo/gofnext/blob/1b88216c6cbcebb4a0e2be1e14bbb32c13955f8f/go.mod#L3C1-L3C10
